# permissions for end users to view echoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: echo-viewer-role
rules:
- apiGroups:
  - testapp.my.domain
  resources:
  - echoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - testapp.my.domain
  resources:
  - echoes/status
  verbs:
  - get
